/*
 * This source file was generated by the Gradle 'init' task
 */
package lab4;

import java.util.Scanner;

import lab4.formater.*;

public class UserSubSystem {

    Team team;

    TeamFormater teamFormater;
    public static void main(String[] args) {
        UserSubSystem userSubSystem = new UserSubSystem();
        Student creator = new Student("2023301350", "张三", "12345678901", "haomingbai@hotmail.com", "Material School", "2023301350", false, 2023);
        Student student1 = new Student("2023301351", "李四", "12345678902", "shiyuanlv@hotmail.com", "Material School", "2023301351", false, 2023);
        Student student2 = new Student("2023301352", "王五", "12345678903", "shangliu@mail.nwpu.edu.cn", "Material School", "2023301352", false, 2023);
        Teacher teacher1 = new Teacher("2023301353", "赵六", "12345678904", "xie.zhang@nwpu.edu.cn", "Material School", "2023301353");
        Teacher teacher2 = new Teacher("2023301354", "孙七", "12345678905", "hui_chen@nwpu.edu.cn", "Material School", "2023301354");
        userSubSystem.team = new Team("2023301355", "软件工程", "Material School", creator);

        userSubSystem.team.addStudent(student1);
        userSubSystem.team.addStudent(student2);
        userSubSystem.team.addTeacher(teacher1);
        userSubSystem.team.addTeacher(teacher2);

        Scanner scanner = new Scanner(System.in);

        System.out.println("Please choose the format of the team information: ");
        System.out.println("[0] Quit \n[1] Display team (Plain Text)\n[2] Display team (HTML)\n[3] Display team (XML)");

        while (scanner.hasNextInt()) {
            int choice = scanner.nextInt();
            switch (choice) {
                case 0:
                    System.out.println("Bye!");
                    return;
                case 1:
                    userSubSystem.teamFormater = PlainTextFormaterFactory.createPlainTextFormater();
                    String text = userSubSystem.teamFormater.formatTeam(userSubSystem.team);
                    System.out.println(text);
                    break;
                case 2:
                    userSubSystem.teamFormater = HTMLTeamFormaterFactory.createHTMLTeamFormater();
                    userSubSystem.teamFormater.formatTeam(userSubSystem.team);
                    String html = userSubSystem.teamFormater.formatTeam(userSubSystem.team);
                    System.out.println(html);
                    break;
                case 3:
                    userSubSystem.teamFormater = XMLTeamFormaterFactory.createXMLTeamFormater();
                    userSubSystem.teamFormater.formatTeam(userSubSystem.team);
                    String xml = userSubSystem.teamFormater.formatTeam(userSubSystem.team);
                    System.out.println(xml);
                    break;
                default:
                    System.out.println("Invalid choice!");
                    break;
            }
        }

        scanner.close();
    }
}
