/*
 * This source file was generated by the Gradle 'init' task
 */
package lab3;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.List;

public class App {

    private static BufferedReader stdIn = new BufferedReader(new InputStreamReader(System.in));
    private static PrintWriter stdOut = new PrintWriter(System.out, true);
    private static PrintWriter stdErr = new PrintWriter(System.err, true);

    private CoffeeShop coffeeShop;

    private static final int MIN_NUMBER = 0;

    private static final int MAX_NUMBER = 50;

    private static final double MIN_COST = 2.0;

    private static final double MAX_COST = 50.0;

    public static void main(String[] args) throws IOException {

        App application = new App();

        application.run();
    }

    private void run() throws IOException {

        coffeeShop = new CoffeeShop();

        int choice = 0;
        try {
            choice = getChoice();
        } catch (Exception e) {
            // TODO: handle exception
            stdOut.println(e.getMessage());
        }
        while (choice != 0) {

            if (choice == 1) {

                try {
                    coffeeShop.addCoffee(readCoffee());
                } catch (Exception e) {
                    stdErr.println(e.getMessage());
                }
            } else if (choice == 2) {

                stdOut.println(coffeeShop.toString());
            } else if (choice == 3) {

                stdOut.println("Total Cost: " + coffeeShop.getTotalCost());
            }

            try {
                choice = getChoice();
            } catch (Exception e) {
                stdErr.println(e.getMessage());
            }
        }
    }

    private int getChoice() throws IOException {
        int choice = stdIn.readLine().charAt(0) - '0';
        if (choice < MIN_NUMBER || choice > MAX_NUMBER) {
            throw new IOException("Invalid choice");
        }
        return choice; // you need to change it.
    }

    private Coffee readCoffee() throws IOException {

        String line = stdIn.readLine();
        List<String> commandList = List.of(line.split("_"));
        // id_name_taste_cost
        if (commandList.size() != 4) {
            throw new IOException("Invalid command");
        }
        int id = Integer.parseInt(commandList.get(0));
        if (id < MIN_NUMBER || id > MAX_NUMBER) {
            throw new IOException("Invalid id");
        }
        String name = commandList.get(1);
        String taste = commandList.get(2);
        double cost = Double.parseDouble(commandList.get(3));
        if (cost < MIN_COST || cost > MAX_COST) {
            throw new IOException("Invalid cost");
        }
        return new Coffee(id, name, taste, cost);
    }
}