/*
 * This source file was generated by the Gradle 'init' task
 */
package cn.edu.nwpu;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CareerConsultingSystemTest {

}
