/*
 * This source file was generated by the Gradle 'init' task
 */
package lab4;

public class UserSubSystem {

    Team team;

    TeamFormater teamFormater;
    public static void main(String[] args) {
    }
}
